config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
  get    '/newpost',   to: 'posts#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_create :create_remember_digest
	attr_accessor :remember_token
	has_secure_password

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		                                              BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	private

		# Creates and assigns the activation token and digest.
	    def create_remember_digest
	      remember_token  = User.new_token
	      self.remember_digest = User.digest(remember_token)
	    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :logged_in?

	# Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
		cookies.permanent[:remember_token] = User.new_token
	end

	# Returns the current logged-in user (if any).
	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:user_id]
			user = User.find_by(id: cookies.signed[:user_id])
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def current_user=(user)
	    @current_user = user
	end

	def log_out(user)
		cookies.delete(:user_id)
    	cookies.delete(:remember_token)
    	session.delete(:user_id)
    	@current_user = nil
	end

	# Returns true if the user is logged in, false otherwise.
	def logged_in?
		!current_user.nil?
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :logged_in?, :only => [:new, :create]

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(title: params[:post][:title],
                         body: params[:post][:body],
                         user_id: current_user.id)
		if @post.save
	      	redirect_to posts_path
	    else
	      	render 'new'
	    end
	end

	def index
		@posts=Post.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		#log in user
  		log_in user
  		redirect_to root_url
  	else
  		#don't log in user
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  		log_out @current_user	
  		redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          <li><%= link_to "Create New Post", newpost_path %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header'%>
  	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
	<% if logged_in? %>
		<h4>Author: <%= User.find(post.user_id).name %></h4> 
	<% end %>
	<h5>Title: <%= post.title %></h5>
	<%= post.body %>
</li>

app/views/posts/create.html.erb
<h1>Posts#create,</h1>
<p>Find me in app/views/posts/create,.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul class="posts">
	<%= render @posts %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for(:post, url: posts_path) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>